[package]
name = "redis_space_check"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
indicatif = "0.17.8"
itertools = "0.13.0"
rand = "0.8.5"
redis = "0.22.3"
uuid = { version = "1.10.0", features = ["v4"] }
